apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apple-ingress
  namespace: default
  labels:
    app: apple
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/apple"
        backend:
          service:
            name: apple
            port: 
              number: 80
  - host: apple-ingress.mgmt.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: apple
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banana-ingress
  namespace: default
  labels:
    app: banana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/banana"
        backend:
          service:
            name: banana
            port: 
              number: 80
  - host: banana-ingress.mgmt.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: banana
            port: 
              number: 80            

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springapp-ingress
  namespace: springapp
  labels:
    app: springapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: sprinapp.mgmt.ocelottraining.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: springapp-svc
            port: 
              number: 8080